services:
  # Backend
  - type: web
    name: turnero-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: "5000"
      - key: CLIENT_URL
        fromService:
          type: web
          name: turnero-client
          property: host
      - key: NODE_ENV
        value: production

  # Frontend
  - type: web
    name: turnero-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: turnero-server
          property: host
